{{- if .Values.githubConfigSecret.github_token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arc-custom-runner.fullname" . }}-github-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arc-custom-runner.labels" . | nindent 4 }}
type: Opaque
data:
  github_token: {{ .Values.githubConfigSecret.github_token | b64enc | quote }}
{{- end }}
{{- if and .Values.githubConfigSecret.github_app_id .Values.githubConfigSecret.github_app_private_key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arc-custom-runner.fullname" . }}-github-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "arc-custom-runner.labels" . | nindent 4 }}
type: Opaque
data:
  github_app_id: {{ .Values.githubConfigSecret.github_app_id | b64enc | quote }}
  github_app_installation_id: {{ .Values.githubConfigSecret.github_app_installation_id | b64enc | quote }}
  github_app_private_key: {{ .Values.githubConfigSecret.github_app_private_key | b64enc | quote }}
{{- end }}
